FROM trinodb/trino:latest

LABEL Wenxiang Liu <liufreeo@gmail.com>



COPY configs/core-site.xml /etc/trino/cluster/core-site.xml
COPY configs/hdfs-site.xml /etc/trino/cluster/hdfs-site.xml
COPY configs/hive.properties /etc/trino/catalog/hive.properties

