FROM liufree/fedora:latest

LABEL Wenxiang Liu <liufreeo@gmail.com>


COPY configs/core-site.xml /data/presto/etc/cluster/core-site.xml
COPY configs/hdfs-site.xml /data/presto/etc/cluster/hdfs-site.xml
COPY configs/hive.properties /data/presto/etc/catalog/hive.properties

